Update publish behavior

diff --git a/rublog b/rublog
--- a/rublog
+++ b/rublog
@@ -92,17 +92,19 @@ class Rublog
     rm -rf ./dist && mkdir ./dist
     echo "mv #{OUTPUT_PATH}{.,}/* ./dist/"
     mv "#{OUTPUT_PATH}"/* ./dist/ ; mv "#{OUTPUT_PATH}"/.* ./dist/
-    touch ./forecestash && git add . && git stash
-    (git checkout --orphan gh-pages || git checkout gh-pages) && git branch --set-upstream-to=origin/gh-pages gh-pages && git pull
-    find . -type d \\( -path ./.git -o -path ./dist \\) -prune -o -exec rm -rf {} \\; 2> /dev/null
-    # mv ./dist/{.,}* . # syntax fail with bash in ruby :/
-    mv "./dist/"/* . ; mv "./dist/"/.* .
-    rmdir ./dist
-    git add . && git commit -am 'Publish auto commit'
-    git push origin gh-pages
-    git checkout -
-    git stash apply && git stash drop
-    rm ./forecestash
+    (git checkout --orphan gh-pages || git checkout gh-pages)
+    if [ $? -eq 0 ]; then
+      git branch --set-upstream-to=origin/gh-pages gh-pages && git pull
+      find . -type d \\( -path ./.git -o -path ./dist \\) -prune -o -exec rm -rf {} \\; 2> /dev/null
+      # mv ./dist/{.,}* . # syntax fail with bash in ruby :/
+      mv "./dist/"/* . ; mv "./dist/"/.* .
+      rmdir ./dist
+      git add .
+      git commit -am 'Publish auto commit' && git push origin gh-pages
+      git checkout -
+    else
+        echo Please commit before publish.
+    fi
     `
   end
 
